name: autofix.ci

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  apply:
    name: Apply automated fixes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup toolchains
        uses: moonrepo/setup-toolchain@827700d97fe7dd1c3030018529e43e23c377c308 # v0
        with:
          auto-install: true
      - name: Install Dependencies
        run: bun ci
      - name: Format code
        run: bun biome check --write
      - name: Fix package.json
        run: bun syncpack fix
      - name: Format package.json
        run: bun syncpack format
      - name: Update package lock file
        run: bun i
      - name: Submit autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1
